feat!: Change sums to be over TypeRows rather than Types
CQCL/hugr pull request #863
Opened 2024-03-06 10:08 UTC by doug-q

2024-03-06 10:45 UTC, doug-q commented on src/ops/controlflow.rs
> -fn tuple_sum_first(tuple_sum_row: &TypeRow, rest: &TypeRow) -> TypeRow {
I have replaced uses with the new `TypeRow::extend`

2024-03-07 11:04 UTC, aborgna-q commented on src/types/check.rs
> +    /// Check that a [`Value`] is a valid instance of this [`crate::types::SumType`].
```suggestion
    /// Check that a [`Value`] is a valid instance of this [`SumType`].
    ///
    ///   [`SumType`]: crate::types::SumType
```
So the link text is just the type

2024-03-07 11:31 UTC, cqc-alec requested changes
Looks good! Just a few comments.

2024-03-07 11:31 UTC, cqc-alec commented on src/hugr/serialize.rs
> +    V1(SerHugrV1),
Add docstring for V1?

2024-03-07 11:31 UTC, cqc-alec commented on src/hugr/serialize.rs
> +struct SerHugrV1 {
I suppose we don't need `SerHugrV0` any more and can delete the struct definition?

2024-03-07 11:31 UTC, cqc-alec commented on src/types.rs
> +/// TODO
Add docstring.

2024-03-07 11:31 UTC, cqc-alec commented on src/types.rs
> +    /// TODO
Add docstring.

2024-03-07 11:31 UTC, cqc-alec commented on specification/schema/hugr_schema_v1.json
> +                    "title": "Tuple Sum Rows",
```suggestion
                    "title": "Sum Rows",
```

2024-03-07 11:31 UTC, cqc-alec commented on specification/hugr.md
> +The three nodes labelled "Tag 0" are simply generating a 1-variant unary Sum (i.e. a Sum one variant with empty rows) to the Output node.
```suggestion
The three nodes labelled "Tag 0" are simply generating a 1-variant unary Sum (i.e. a Sum of one variant with empty rows) to the Output node.
```

2024-03-11 09:25 UTC, doug-q commented on justfile
> +    cargo clippy --all-targets --all-features --workspace --fix --allow-staged --allow-dirty
This slipped in, but I do think it's an improvement (I usually have some untracked files). I will raise at standup and remove from here if there is less than unanimous agreement.

2024-03-12 13:24 UTC, doug-q commented on justfile
> +    cargo clippy --all-targets --all-features --workspace --fix --allow-staged --allow-dirty
Removed this

2024-03-12 13:49 UTC, cqc-alec approved these changes
Just a couple of pedantries.

2024-03-12 13:49 UTC, cqc-alec commented on quantinuum-hugr/src/ops/constant.rs
> +    /// Creates a new Const Sum.  The value determined by `items` and is
```suggestion
    /// Creates a new Const Sum.  The value is determined by `items` and is
```

2024-03-12 13:49 UTC, cqc-alec commented on specification/hugr.md
> +The three nodes labelled "Tag 0" are simply generating a 1-variant unary Sum (i.e. a Sum  of one variant with empty rows) to the Output node.
```suggestion
The three nodes labelled "Tag 0" are simply generating a 1-variant unary Sum (i.e. a Sum of one variant with empty rows) to the Output node.
```

2024-03-12 14:15 UTC, aborgna-q commented on quantinuum-hugr/src/ops/constant.rs
>      ) -> Result<Self, ConstTypeError> {
Yes, that makes sense.

2024-03-12 14:17 UTC, merged